services:
  app:
    build: .
    container_name: vysota-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
      - DATABASE_PATH=/app/backend/database.db
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    command: python backend/app.py
    restart: unless-stopped